/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CarsCarousel: typeof import('./src/components/CarsComponents/CarsCarousel.vue')['default']
    CarsFilo: typeof import('./src/components/CarsComponents/CarsFilo.vue')['default']
    FooterComponent: typeof import('./src/components/GlobalComponents/FooterComponent.vue')['default']
    HeaderComponent: typeof import('./src/components/GlobalComponents/HeaderComponent.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    LogoComponent: typeof import('./src/components/GlobalComponents/LogoComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopNavComponent: typeof import('./src/components/GlobalComponents/TopNavComponent.vue')['default']
  }
}
