/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddressComponent: typeof import('./src/components/ContactComponents/AddressComponent.vue')['default']
    AdressComponent: typeof import('./src/components/ContactComponents/AdressComponent.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    BaseButton: typeof import('./src/components/GlobalComponents/BaseComponents/BaseButton.vue')['default']
    BaseForm: typeof import('./src/components/GlobalComponents/BaseComponents/BaseForm.vue')['default']
    CarsCarousel: typeof import('./src/components/CarsComponents/CarsCarousel.vue')['default']
    CarsFilo: typeof import('./src/components/CarsComponents/CarsFilo.vue')['default']
    FooterComponent: typeof import('./src/components/GlobalComponents/Footer/FooterComponent.vue')['default']
    GoogleMap: typeof import('./src/components/GoogleMap.vue')['default']
    HeaderComponent: typeof import('./src/components/GlobalComponents/Header/HeaderComponent.vue')['default']
    HumburgerComponent: typeof import('./src/components/GlobalComponents/Header/HumburgerComponent.vue')['default']
    'Icon:bx:bxMoon': typeof import('~icons/bx/bx-moon')['default']
    'Icon:bx:bxsMoon': typeof import('~icons/bx/bxs-moon')['default']
    'IconAkarIcons:githubFill': typeof import('~icons/akar-icons/github-fill')['default']
    LogoComponent: typeof import('./src/components/GlobalComponents/Header/LogoComponent.vue')['default']
    NedenBizComponent: typeof import('./src/components/FirstPageComponents/NedenBizComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideNavComponent: typeof import('./src/components/GlobalComponents/Header/SideNavComponent.vue')['default']
    TopFooterCard: typeof import('./src/components/GlobalComponents/Footer/TopFooterCard.vue')['default']
    TopNavComponent: typeof import('./src/components/GlobalComponents/Header/TopNavComponent.vue')['default']
    VisiyonMisiyon: typeof import('./src/components/AboutUsComponents/VisiyonMisiyon.vue')['default']
    WhyFiloComponent: typeof import('./src/components/FirstPageComponents/WhyFiloComponent.vue')['default']
  }
}
